[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18.18.0"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml"
